### PR TITLE
Bruh

### PR DESCRIPTION
**Pull request by darkdarcool**
Make your MD better with proper MD lol

### CODE REVIEW

**Comment by JBYT27** [comment]
im confused, whats the difference lol

**Comment by darkdarcool** [comment]
I made a >

Its proper to make a footer like that if you have one in an MD

**Comment by JBYT27** [comment]
Oh, ok. I'll merge then

**Comment by darkdarcool** [comment]
k cool. also can you go to excalibur?

**Comment by JBYT27** [comment]
Sorry, just saw notif, I'll be on, but I'm not sure if you will

**Comment by darkdarcool** [comment]
ok

**Pull request merged**
