### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by JBYT27**
Creating `.gitignore`.

### CODE REVIEW

**Comment by JBYT27** [comment]
Hiya @darkdarcool, quick question, I have a `__pycache__` directory, so I made a `.gitignore`, to ignore that directory. However, should I just leave the `.gitignore`? Or should I delete that?

Thanks!

**Comment by darkdarcool** [comment]
You have to have the gitignore to ignore files, when you delete the pycache will come back

**Comment by JBYT27** [comment]
So what should I do?

**Comment by darkdarcool** [comment]
Keep the gitignore?

**Comment by JBYT27** [comment]
Oh, ok, thanks! :D

**Comment by darkdarcool** [comment]
YW

**Pull request merged**
